language: python

services:
  - docker
  
before_install:
  # Run TestSuite
  - cd ./test_suite
  - docker-compose up -d
  - cd ..
  
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build

install:
  - pip install -r requirements.txt

script:
  - pytest tests/test_encryption.py
  - pytest tests/test_messages.py
  - pytest tests/test_agent.py
