language: python

services:
  - docker
  
env:
  - TEST_SUITE_BASE_URL=http://localhost INDY_AGENT_BASE_URL=http://127.0.0.1:88
  
before_install:
  # Run TestSuite
  - cd ./test_suite
  - docker-compose up -d
  - cd ..
  - sleep 60  # Wait for TestSuite is ready
  
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "nightly"  # nightly build

install:
  - pip install -r requirements.txt

script:
  - pytest
