language: python

services:
  - docker
  
before_install:
  # Run TestSuite
  - cd ./test_suite
  - docker-compose up -d
  - cd ..
  - sleep 60  # Wait for TestSuite is ready
  
python:
#  - "3.6"      # current default Python on Travis CI
#  - "3.7"
  - "3.8"
#  - "nightly"  # nightly build

install:
  - pip install -r requirements.txt

script:
  - pytest tests/test_messages
  - pytest tests/test_encryption
  - pytest tests/test_future_promise
  - pytest tests/test_agent
  - pytest tests/test_storages
  - pytest tests/test_microledgers
  - pytest tests/test_ledgers
  - pytest tests/test_coprotocols
  - pytest tests/test_consensus_simple
  - pytest tests/test_0160_conn_protocol
  - pytest tests/test_0036_issue_credential
  - pytest tests/test_0037_verify_proof
  - pytest tests/test_performance
